Server: "apps/server/**/*"
Web: "apps/web/**/*"
Auth Providers: "packages/auth-providers/**/*"
ESLint Config Custom: "packages/eslint-config-custom/**/*"
Prisma Client: "packages/prisma-client/**/*"
Shared Library: "packages/shared-lib/**/*"
TRPC: "packages/trpc/**/*"
TS Config: "packages/tsconfig/**/*"

Documentation: "README.md"

Turbo Setup: "{tsconfig.json,package.json,package-lock.json,yarn-lock.json,!(packages|apps|.github|.hooks|)/**/*}"

Github Actions:
  - any: [".github/**/*"]

Pre-commit Hooks:
  - any: [".hooks/**/*", ".husky/**/*"]
