"@RoomParty/server": "./apps/server/**/*"
"@RoomParty/web": "./apps/web/**/*"
"@RoomParty/auth-providers": "./packages/auth-providers/**/*"
"@RoomParty/eslint-config-custom": "./packages/eslint-config-custom/**/*"
"@RoomParty/prisma-client": "./packages/prisma-client/**/*"
"@RoomParty/shared-lib": "./packages/shared-lib/**/*"
"@RoomParty/trpc": "./packages/trpc/**/*"
"@RoomParty/tsconfig": "./packages/tsconfig/**/*"

Documentation: "README.md"

Turbo Setup: "{tsconfig.json,package.json,package-lock.json,yarn-lock.json,!(packages|apps|.github|.hooks|)/**/*}"

Github Actions:
  - any: [".github/**/*"]

Pre-commit Hooks:
  - any: [".hooks/**/*", ".husky/**/*"]
