version: "3"

services:
  base:
    environment:
      - SERVER_PORT
      - NEXT_PUBLIC_SERVER_URL
      - SERVER_URL
      - DATABASE_URL
      - NEXT_PUBLIC_WEBSOCKET_URL
      - WEB_BASE_URL
      - NEXT_PUBLIC_WEB_BASE_URL
      - NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_ID
      - NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_SECRET
      - GOOGLE_OAUTH_CLIENT_SECRET
      - NEXT_PUBLIC_GOOGLE_WEB_OAUTH_CLIENT_SECRET
      - GOOGLE_WEB_OAUTH_CLIENT_SECRET
      - NEXT_PUBLIC_GOOGLE_WEB_OAUTH_CLIENT_ID
      - GOOGLE_WEB_OAUTH_CLIENT_ID
      - SERVER_SESSION_SECRET
      - SERVER_JWT_SECRET
