version: "3"

services:
  server:
    container_name: server
    extends:
      file: base.yml
      service: base
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        - DATABASE_URL
    restart: always
    ports:
      - 8000:8000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
