version: "2"

services:
  server:
    platform: linux/amd64
    container_name: server
    extends:
      file: base.yml
      service: base
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        - SERVER_PORT
        - NEXT_PUBLIC_SERVER_URL
        - SERVER_URL
        - DATABASE_URL
        - NEXT_PUBLIC_WEBSOCKET_URL
        - WEB_BASE_URL
        - NEXT_PUBLIC_WEB_BASE_URL
        - NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID
        - GOOGLE_OAUTH_CLIENT_ID
        - NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_SECRET
        - GOOGLE_OAUTH_CLIENT_SECRET
        - NEXT_PUBLIC_GOOGLE_WEB_OAUTH_CLIENT_SECRET
        - GOOGLE_WEB_OAUTH_CLIENT_SECRET
        - NEXT_PUBLIC_GOOGLE_WEB_OAUTH_CLIENT_ID
        - GOOGLE_WEB_OAUTH_CLIENT_ID
        - SERVER_SESSION_SECRET
        - SERVER_JWT_SECRET
        - NODE_TLS_REJECT_UNAUTHORIZED
    restart: always
    ports:
      - 8000:8000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
