name: Code Coverage Reporter

on:
  pull_request:
    branches: [main, develop, staging]

jobs:
  label:
    runs-on: ubuntu-latest
    env:
      OS: ${{ matrix.os }}
      PYTHON: "3.7"

    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
