name: Code Coverage Reporter

on:
  pull_request:
    branches: [main, develop, staging]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
