name: PR Labeler

on:
  pull_request:
    branches: [main, develop, staging]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Add Label Based on Files Changes
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.ACCESS_TOKEN }}"
          sync-labels: true

      - name: Add Labels Based on Branch Name
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler-by-branch-name.yml
        env:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
